version: '3'
services:
  app:
    restart: always
    build: .
    hostname: visao-{{.Task.Slot}}
    networks:
      - visao
    environment:
      CMD_Python: python3
      PORT_DOCKER: 3005
      API_PORT: 3005
    ports:
      - 3005-3008:3005
    deploy:
      replicas: 4
      placement:
        constraints:
          - node.role == worker
  nginx:
    restart: always
    image: nginx
    networks:
      - visao
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
networks:
  visao:
    driver: bridge