version: '3'
services:
  app:
    restart: always
    build: .
    hostname: visao-{{.Task.Slot}}
    networks:
      - visao
    environment:
      CMD_Python: python3
      PORT_DOCKER: 3005
      API_PORT: 3005
    ports:
      - "3005:3005"
networks:
  visao:
    driver: bridge